### ISSUE TITLE
DFD Comments

### ISSUE THREAD

**Issue by germonprez** [maldhahri/3420ISQA#3]
Hey, 

Here are some comments: 

1) The DB should not send results directly to the Developer as I talked about in class. 
2) Check OSS Components will sent OSS Results to the DB as well as back to the Developer. Make your processes do the work. 

MG

**Comment by maldhahri** [comment]
[DB 222333.pdf](https://github.com/maldhahri/3420ISQA/files/752728/DB.222333.pdf)

**Comment by maldhahri** [comment]
![db 000](https://cloud.githubusercontent.com/assets/25205471/22623537/1c1fd98e-eb24-11e6-8512-8c0d21bc3db1.jpg)

**Comment by maldhahri** [comment]
image uploaded
